Repository devchallenge-io/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#1 feat: update readme
  README.md
  low-code/README.md
  non-code/README.md
  resolucoes/javascript-lorenalgm.md
Labels: enhancement

#5 Desafio 1 Concluido
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/.eslintrc.json
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/.gitignore
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/README.md
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/next.config.js
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/package.json
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/pages/_app.js
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/pages/author/[id].js
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/pages/index.js
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/pages/post/[id].js
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/public/favicon.ico
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/public/jamstack.svg
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/public/logo.svg
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/services/api.js
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/styles/Author.module.css
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/styles/Home.module.css
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/styles/globals.css
  desafios/desafio1/resolucoes/desafio1-filipeleonelbatista/yarn.lock
  resolucoes/desafio1-filipeleonelbatista/.eslintrc.json
  resolucoes/desafio1-filipeleonelbatista/.gitignore
  resolucoes/desafio1-filipeleonelbatista/README.md
  resolucoes/desafio1-filipeleonelbatista/next.config.js
  resolucoes/desafio1-filipeleonelbatista/package.json
  resolucoes/desafio1-filipeleonelbatista/pages/_app.js
  resolucoes/desafio1-filipeleonelbatista/pages/author/[id].js
  resolucoes/desafio1-filipeleonelbatista/pages/index.js
  resolucoes/desafio1-filipeleonelbatista/pages/post/[id].js
  resolucoes/desafio1-filipeleonelbatista/public/favicon.ico
  resolucoes/desafio1-filipeleonelbatista/public/jamstack.svg
  resolucoes/desafio1-filipeleonelbatista/public/logo.svg
  resolucoes/desafio1-filipeleonelbatista/services/api.js
  resolucoes/desafio1-filipeleonelbatista/styles/Author.module.css
  resolucoes/desafio1-filipeleonelbatista/styles/Home.module.css
  resolucoes/desafio1-filipeleonelbatista/styles/globals.css
  resolucoes/desafio1-filipeleonelbatista/yarn.lock
Labels: enhancement

#6 feat: solid srp principle article in react
  low-code/solid-srp-react-lucas0019/react/exemplo-com-srp.jsx
  low-code/solid-srp-react-lucas0019/react/exemplo-sem-srp.jsx
  low-code/solid-srp-react-lucas0019/srp.md
Labels: documentation, enhancement

#12 Devchallenge - Desafio 05
  desafios/desafio5/assets/capa-filme-1.png
  desafios/desafio5/assets/capa-filme-2.png
  desafios/desafio5/assets/capa-filme-3.png
  desafios/desafio5/assets/icon-home.svg
  desafios/desafio5/assets/icon-notification.svg
  desafios/desafio5/assets/icon-search.svg
  desafios/desafio5/assets/icon-user.svg
  desafios/desafio5/assets/perfil.png
  desafios/desafio5/desafio.md
Labels: hacktoberfest-accepted

#13 Feat/challenge01
  resolucoes/desafio1-jhonatasmatos/.babelrc
  resolucoes/desafio1-jhonatasmatos/.env.example
  resolucoes/desafio1-jhonatasmatos/.eslintrc.json
  resolucoes/desafio1-jhonatasmatos/.gitignore
  resolucoes/desafio1-jhonatasmatos/README.md
  resolucoes/desafio1-jhonatasmatos/next.config.js
  resolucoes/desafio1-jhonatasmatos/package-lock.json
  resolucoes/desafio1-jhonatasmatos/package.json
  resolucoes/desafio1-jhonatasmatos/postcss.config.js
  resolucoes/desafio1-jhonatasmatos/public/favicon.ico
  resolucoes/desafio1-jhonatasmatos/public/jamstack.svg
  resolucoes/desafio1-jhonatasmatos/public/vercel.svg
  resolucoes/desafio1-jhonatasmatos/services/data.js
  resolucoes/desafio1-jhonatasmatos/src/helpers/dateConverter.js
  resolucoes/desafio1-jhonatasmatos/src/pages/_app.js
  resolucoes/desafio1-jhonatasmatos/src/pages/index.jsx
  resolucoes/desafio1-jhonatasmatos/src/pages/post/[slug].jsx
  resolucoes/desafio1-jhonatasmatos/styles/globals.css
  resolucoes/desafio1-jhonatasmatos/tailwind.config.js
Labels: hacktoberfest-accepted

#15 desafio 3
  resolucoes/desafio3-filipeleonelbatista/.gitignore
  resolucoes/desafio3-filipeleonelbatista/index.html
  resolucoes/desafio3-filipeleonelbatista/package.json
  resolucoes/desafio3-filipeleonelbatista/public/vite.svg
  resolucoes/desafio3-filipeleonelbatista/src/App.css
  resolucoes/desafio3-filipeleonelbatista/src/App.jsx
  resolucoes/desafio3-filipeleonelbatista/src/assets/react.svg
  resolucoes/desafio3-filipeleonelbatista/src/index.css
  resolucoes/desafio3-filipeleonelbatista/src/main.jsx
  resolucoes/desafio3-filipeleonelbatista/vite.config.js
  resolucoes/desafio3-filipeleonelbatista/yarn.lock
Labels: hacktoberfest-accepted

#17 Feat/challenge02
  resolucoes/desafio2-jhonatasmatos/.gitignore
  resolucoes/desafio2-jhonatasmatos/index.html
  resolucoes/desafio2-jhonatasmatos/package-lock.json
  resolucoes/desafio2-jhonatasmatos/package.json
  resolucoes/desafio2-jhonatasmatos/postcss.config.cjs
  resolucoes/desafio2-jhonatasmatos/public/vite.svg
  resolucoes/desafio2-jhonatasmatos/src/App.jsx
  resolucoes/desafio2-jhonatasmatos/src/Router.jsx
  resolucoes/desafio2-jhonatasmatos/src/assets/Logo.png
  resolucoes/desafio2-jhonatasmatos/src/assets/flags/br.png
  resolucoes/desafio2-jhonatasmatos/src/assets/flags/es.png
  resolucoes/desafio2-jhonatasmatos/src/assets/flags/fr.png
  resolucoes/desafio2-jhonatasmatos/src/assets/flags/it.png
  resolucoes/desafio2-jhonatasmatos/src/assets/flags/ng.png
  resolucoes/desafio2-jhonatasmatos/src/assets/flags/pt.png
  resolucoes/desafio2-jhonatasmatos/src/assets/react.svg
  resolucoes/desafio2-jhonatasmatos/src/assets/soccer_field.png
  resolucoes/desafio2-jhonatasmatos/src/assets/soccer_play.jpg
  resolucoes/desafio2-jhonatasmatos/src/assets/soccer_player.png
  resolucoes/desafio2-jhonatasmatos/src/assets/soccer_player2.png
  resolucoes/desafio2-jhonatasmatos/src/assets/world_cup.jpg
  resolucoes/desafio2-jhonatasmatos/src/components/Footer.jsx
  resolucoes/desafio2-jhonatasmatos/src/components/Header.jsx
  resolucoes/desafio2-jhonatasmatos/src/components/ScoreBoard.jsx
  resolucoes/desafio2-jhonatasmatos/src/components/TextInput.jsx
  resolucoes/desafio2-jhonatasmatos/src/main.jsx
  resolucoes/desafio2-jhonatasmatos/src/pages/Guess.jsx
  resolucoes/desafio2-jhonatasmatos/src/pages/Winner.jsx
  resolucoes/desafio2-jhonatasmatos/src/styles/global.css
  resolucoes/desafio2-jhonatasmatos/src/utils/data.json
  resolucoes/desafio2-jhonatasmatos/src/utils/getFlags.js
  resolucoes/desafio2-jhonatasmatos/tailwind.config.cjs
  resolucoes/desafio2-jhonatasmatos/vite.config.js
Labels: hacktoberfest-accepted

#20 Feat/challenge03
  resolucoes/desafio3-jhonatasmatos/.gitignore
  resolucoes/desafio3-jhonatasmatos/index.html
  resolucoes/desafio3-jhonatasmatos/package-lock.json
  resolucoes/desafio3-jhonatasmatos/package.json
  resolucoes/desafio3-jhonatasmatos/public/vite.svg
  resolucoes/desafio3-jhonatasmatos/src/App.css
  resolucoes/desafio3-jhonatasmatos/src/App.jsx
  resolucoes/desafio3-jhonatasmatos/src/assets/react.svg
  resolucoes/desafio3-jhonatasmatos/src/index.css
  resolucoes/desafio3-jhonatasmatos/src/main.jsx
  resolucoes/desafio3-jhonatasmatos/vite.config.js
Labels: hacktoberfest-accepted
